#!/usr/bin/env bash
set -Eeuo pipefail
trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
      exit $ec;' ERR

die()  { ec="$1"; shift; echo 1>&2 "ERROR ($ec):" "$@"; exit $ec; }
fail() { ec=$?; echo "FAILED exitcode=$ec ($(elapsed)s)"; exit $ec; }

elapsed_start=$(date +%s)
elapsed() { echo $(( $(date +%s) - $elapsed_start )); }

####################################################################

PROJDIR=$(cd $(dirname "$0") && pwd -P)

skip_typecheck=false
while [[ $# -gt 0 ]]; do case "$1" in
    -C)     shift; rm -rf "$PROJDIR/.build/";;
    -c)     shift; rm -rf "$PROJDIR/.build/"{cache,virtualenv};;
    -T)     shift; skip_typecheck=true;;
    *)      break;;
esac; done

. $PROJDIR/pactivate -q

####################################################################

if $skip_typecheck; then
    echo 'WARNING: Skipping typecheck.'
else
    echo -n 'mypy: '
    PYTHONPATH=src/ mypy        # Config in pyproject.toml.
fi

pytest "$@" || fail
